// Code generated by templ@v0.2.364 DO NOT EDIT.

package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	db "myapp/DB"
)

func FoodSearch(foods []db.Food) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<h1>")
		if err != nil {
			return err
		}
		var_2 := `Food in base 100g `
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><input type=\"search\" placeholder=\"Search...\" name=\"search\" hx-get=\"food_search\" hx-select=\"#search-results\" hx-trigger=\"keyup changed delay:500ms, search\" hx-target=\"#search-results\" hx-swap=\"outerHTML\"><table><thead><th scope=\"col\">")
		if err != nil {
			return err
		}
		var_3 := `Name `
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th><th scope=\"col\">")
		if err != nil {
			return err
		}
		var_4 := `Calories `
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th><th scope=\"col\">")
		if err != nil {
			return err
		}
		var_5 := `Protein `
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th><th scope=\"col\">")
		if err != nil {
			return err
		}
		var_6 := `Fat `
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th><th scope=\"col\">")
		if err != nil {
			return err
		}
		var_7 := `Carb`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th></thead><tbody id=\"search-results\">")
		if err != nil {
			return err
		}
		for _, food := range foods {
			_, err = templBuffer.WriteString("<tr><th scope=\"row\">")
			if err != nil {
				return err
			}
			var var_8 string = food.Name
			_, err = templBuffer.WriteString(templ.EscapeString(var_8))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th>")
			if err != nil {
				return err
			}
			var var_9 string = fmt.Sprintf("%.1f", food.Macros.Calories)
			_, err = templBuffer.WriteString(templ.EscapeString(var_9))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th>")
			if err != nil {
				return err
			}
			var var_10 string = fmt.Sprintf("%.1f", food.Macros.Protein)
			_, err = templBuffer.WriteString(templ.EscapeString(var_10))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th>")
			if err != nil {
				return err
			}
			var var_11 string = fmt.Sprintf("%.1f", food.Macros.Fat)
			_, err = templBuffer.WriteString(templ.EscapeString(var_11))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th>")
			if err != nil {
				return err
			}
			var var_12 string = fmt.Sprintf("%.1f", food.Macros.Carb)
			_, err = templBuffer.WriteString(templ.EscapeString(var_12))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</th><th><button hx-post=\"join\" name=\"foodID\" value=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(fmt.Sprint(food.ID)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var_13 := `Select `
			_, err = templBuffer.WriteString(var_13)
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</button></th></tr>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</tbody></table><!--")
		if err != nil {
			return err
		}
		var_14 := ` <button hx-get="/food/new/{mealID}" hx-target="#search-results" hx-swap="afterend"> Create New </button>`
		_, err = templBuffer.WriteString(var_14)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("-->")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
